os: linux

# Install Travis so we can get the token from Travis
before_script:
  - gem install travis

# Do nothing
script:
  - echo "Not doing any work here, will just tell downstream repositories that the Geometrize templates library has been updated"

after_script:
  - chmod +x trigger_travis.sh
  - ./trigger_travis.sh Tw1ddle geometrize master $TRAVIS_ACCESS_TOKEN_GEOMETRIZE_APP_TRIGGER
